on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true
        description: "The config directory to use"
      version:
        type: string
        required: true
        description: "The version tag to fetch, or 'develop', will pick automatically if not passed"
    secrets:
      CONFIG_URL:
        required: true

jobs:
  prepare:
    name: Prepare Web
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          repository: element-hq/element-desktop
          ref: ${{ inputs.version }}

      - uses: actions/checkout@v4
        with:
          path: ./overrides
          ref: web

      - name: Update package.json
        run: |
          mv package.json package.old.json
          jq -s '.[0] * .[1]' package.old.json overrides/package.patch.json > package.json

      - name: Get config
        shell: bash
        run: |
          mkdir -p "${{ inputs.config }}"
          curl -sSfLo "${{ inputs.config }}/config.json" "$CONFIG_URL"
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "yarn"

      - name: Install Deps
        run: "yarn install --frozen-lockfile"

      - name: Fetch Element Web
        run: yarn run fetch --noverify -d "${{ inputs.config }}" ${{ inputs.version }}

      - name: Override web
        run: |
          cp -r overrides/res "deploys/element-${{ inputs.version }}"
          sed -e 's/>Element</Zyfra Talks/' \
            -e 's/content="Element"/content="Zyfra Talks"/' \
            -e "s|https.*opengraph.png|${CONFIG_URL%/*}/zyfra/opengraph.png|" \
            -e 's/Element requires/Zyfra Talks requires/' \
            -i deploys/element-${{ inputs.version }}/index.html
          sed -e "s|https://element.io|${CONFIG_URL%/*}|" \
            -i deploys/element-${{ inputs.version }}/welcome.html
          sed -e "s|https://Element|$CONFIG_DIR|" \
            -e 's/#76CFA6/#1B4A1B/' \
            -i deploys/element-${{ inputs.version }}/manifest.json
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
          CONFIG_DIR: ${{ inputs.config }}

      - name: Pack updated asar
        run: yarn run asar p deploys/element-${{ inputs.version }}/ webapp.asar

      - name: Generate cache hash files
        run: |
          yarn run --silent electron --version > electronVersion
          jq -erc .hakDependencies package.json | sha1sum > hakHash
          find hak -type f -print0 | xargs -0 sha1sum >> hakHash
          find scripts/hak -type f -print0 | xargs -0 sha1sum >> hakHash

      - name: Pack web
        run: |
          mv deploys/element-${{ inputs.version }} web-${{ inputs.version }}
          tar czvf web.tar.gz web-${{ inputs.version }}

      - uses: actions/upload-artifact@v4
        with:
          name: webapp
          retention-days: 1
          path: |
            webapp.asar
            talks-web.tar.gz
            package.json
            ${{ inputs.config }}/config.json
            electronVersion
            hakHash
